version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          name: Restore dependencies cache
          key: dependencies-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save dependencies cache
          key: dependencies-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Lint code
          command: yarn lint
      - run:
          name: Build app
          command: yarn build
      - run:
          name: Start app
          command: yarn start
          background: true
      - run:
          name: Run tests
          command: yarn test
